"""initial schema

Revision ID: b4f53432bf07
Revises: 
Create Date: 2025-08-17 13:37:43.979949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f53432bf07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tree',
    sa.Column('parent_admin_id', sa.Integer(), nullable=False),
    sa.Column('child_admin_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('parent_admin_id', 'child_admin_id'),
    sa.UniqueConstraint('parent_admin_id', 'child_admin_id')
    )
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('campaign_copies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_campaign_id', sa.Integer(), nullable=False),
    sa.Column('to_campaign_id', sa.Integer(), nullable=False),
    sa.Column('from_unit_id', sa.Integer(), nullable=False),
    sa.Column('to_unit_id', sa.Integer(), nullable=False),
    sa.Column('copied_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('copied_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashtag', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('root_campaign_id', sa.Integer(), nullable=True),
    sa.Column('unit_id_owner', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_admin_id'), 'campaigns', ['admin_id'], unique=False)
    op.create_index(op.f('ix_campaigns_root_campaign_id'), 'campaigns', ['root_campaign_id'], unique=False)
    op.create_index(op.f('ix_campaigns_unit_id_owner'), 'campaigns', ['unit_id_owner'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_admin_id'), 'cities', ['admin_id'], unique=False)
    op.create_table('unit_admins',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('unit_id', 'admin_id')
    )
    op.create_index(op.f('ix_unit_admins_admin_id'), 'unit_admins', ['admin_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_units_parent', 'units', ['parent_id'], unique=False)
    op.create_index(op.f('ix_units_parent_id'), 'units', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('unit_id_paygah', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_admin_id'), 'users', ['admin_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('unit_id_owner', sa.Integer(), nullable=True),
    sa.Column('submitted_to_campaign_id', sa.Integer(), nullable=True),
    sa.Column('submitted_to_unit_id', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_campaign_id'), 'reports', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_reports_city_id'), 'reports', ['city_id'], unique=False)
    op.create_index(op.f('ix_reports_platform'), 'reports', ['platform'], unique=False)
    op.create_index(op.f('ix_reports_submitted_to_campaign_id'), 'reports', ['submitted_to_campaign_id'], unique=False)
    op.create_index(op.f('ix_reports_submitted_to_unit_id'), 'reports', ['submitted_to_unit_id'], unique=False)
    op.create_index(op.f('ix_reports_unit_id_owner'), 'reports', ['unit_id_owner'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('report_item_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('source_report_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_item_refs_report_id'), 'report_item_refs', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_item_refs_source_report_item_id'), 'report_item_refs', ['source_report_item_id'], unique=False)
    op.create_table('report_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_items_report_id'), 'report_items', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_items_report_id'), table_name='report_items')
    op.drop_table('report_items')
    op.drop_index(op.f('ix_report_item_refs_source_report_item_id'), table_name='report_item_refs')
    op.drop_index(op.f('ix_report_item_refs_report_id'), table_name='report_item_refs')
    op.drop_table('report_item_refs')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_unit_id_owner'), table_name='reports')
    op.drop_index(op.f('ix_reports_submitted_to_unit_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_submitted_to_campaign_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_platform'), table_name='reports')
    op.drop_index(op.f('ix_reports_city_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_campaign_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_admin_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_parent_id'), table_name='units')
    op.drop_index('idx_units_parent', table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_unit_admins_admin_id'), table_name='unit_admins')
    op.drop_table('unit_admins')
    op.drop_index(op.f('ix_cities_admin_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_campaigns_unit_id_owner'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_root_campaign_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_admin_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('campaign_copies')
    op.drop_table('admins')
    op.drop_table('admin_tree')
    # ### end Alembic commands ###
